{% set name = "eth-utils" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ethereum/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 452bcbbc98d2f8c8822ca5cde7fc0c032581a642ab98567eebd10410d2583729
  patches: # [win]
    - 0001-Change-forward-slash-on-backslash.patch # [win]

build:
  skip: true  # [py<3.8]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build: 
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - eth-hash >=0.3.1
    - eth-typing >=5.0.0
    - toolz >0.8.2 # [python_impl == 'pypy']
    - cytoolz >=0.10.1 # [python_impl == 'cpython']

test:
  source_files:
    - fixtures
    - tests
  imports:
    - eth_utils
    - eth_utils.curried
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - hypothesis >=4.43.0
    - pytest >=7.0.0
    - pytest-xdist >=2.4.0
    - mypy ==1.10.0

about:
  home: https://github.com/ethereum/eth_utils
  summary: Utility functions for working with ethereum related codebases.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ethereum/eth-utils
  doc_url: https://eth-utils.readthedocs.io/en/stable/
  description: Common utility functions for python code that interacts with Ethereum

extra:
  recipe-maintainers:
    - step21
