{% set name = "eth-utils" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ethereum/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 452bcbbc98d2f8c8822ca5cde7fc0c032581a642ab98567eebd10410d2583729

build:
  skip: true  # [py>=40 or py2k]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - eth-hash >=0.3.1
    - eth-typing >=5.0.0
    - toolz >0.8.2
    - cytoolz >=0.10.1
  run_constrained:
    - tox >=4.0.0
    - pre-commit >=3.4.0
    - build >=0.9.0
    - bump_my_version >=0.19.0
    - pycryptodome >=3.6.6,<4

test:
  source_files:
    - fixtures
    - tests
  imports:
    - eth_utils
    - eth_utils.curried
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - hypothesis >=4.43.0
    - pytest >=7.0.0
    - pytest-xdist >=2.4.0
    - mypy ==1.10.0

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ethereum/eth-utils
  doc_url: https://eth-utils.readthedocs.io/en/stable/
  description: Common utility functions for ethereum codebases.

extra:
  recipe-maintainers:
    - step21
